### ISSUE TITLE
Unable to access count.pl and statistics.pl in preprocessing/run.sh

### ISSUE THREAD

**Issue by NikitaGautam** [kilicogluh/lbd-covid#5]
https://github.com/kilicogluh/lbd-covid/tree/master/preprocessing 

For preprocessing, the given code asks you to run "run.sh", where two pearl scripts are called for before finding concept_degree i.e. count.pl and statistics.pl .  In order to run the compute_score script, the script takes concept degree and stats as input to calculate the score.  I was wondering if the scripts were missing or was not provided for other reasons. Also, it would be helpful if you could provide if there are any example files for extracted sub_rel_obj, stats, count, and concept degree from the dataset that you used.

**Comment by rishabh279** [comment]
Concept Degree and Stats are the outputs that you will get by running count.pl and statitics.pl files. Authors have provided every file required to run the codebase. Please follow run.sh step by step. You will get the results as mentioned in the paper. Thanks.

**Comment by NikitaGautam** [comment]
For those who round up with the same issue, install [https://anaconda.org/bioconda/perl-text-nsp] and follow the steps of run.sh.
